
image:
  file: .gitpod.Dockerfile

# List the start up tasks. You can start them in parallel in multiple terminals. See https://www.gitpod.io/docs/44_config_start_tasks/
tasks:
  - init: pip install -r requirements.txt # runs during prebuild
vscode:
  extensions:
    - ms-python.python